extraction:
  cpp:
    after_prepare:    # Customizable step used by all languages.
      - wget https://github.com/jmcnamara/libxlsxwriter/archive/RELEASE_0.8.8.tar.gz
      - tar -zxf RELEASE_0.8.8.tar.gz
      - pushd libxlsxwriter-RELEASE_0.8.8 && make -j2 && popd
    configure:
      command:
        - echo "LIBS += -L/opt/src/libxlsxwriter-RELEASE_0.8.8/lib" >> STIGQter.pro
        - echo "INCLUDEPATH += /opt/src/libxlsxwriter-RELEASE_0.8.8/include /usr/include/tidy" >> STIGQter.pro
        - qmake STIGQter.pro
