language: cpp
compiler: gcc
dist: bionic
services:
        - xvfb

addons:
        sonarcloud:
                organization: "squinky86"
                token:
                        secure: "1627f17c5f4b2974c221d3b6fcd2e0c4bebb6ecf"

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install qtbase5-dev qt5-qmake qt5-default libqt5sql5-sqlite
 - sudo apt-get install libtidy-dev libzip-dev
 - sudo apt-get install zlib1g-dev
 - wget https://github.com/jmcnamara/libxlsxwriter/archive/RELEASE_0.8.8.tar.gz
 - tar -zxf RELEASE_0.8.8.tar.gz
 - pushd libxlsxwriter-RELEASE_0.8.8 && make && sudo make install INSTALL_DIR=/usr && popd
 - pip install --user cpp-coveralls

script:
 - sed -i -e 's:INCLUDEPATH[ ]*=[ ]*:INCLUDEPATH = /usr/include/tidy :g' STIGQter.pro
 - for x in `find /home/travis/.sonar/cache -name "libinterceptor-x86_64.so"`; do cp ${x} ${x/x86_64/haswell}; done
 - echo "DEFINES += USE_TESTS" >> STIGQter.pro
 - qmake STIGQter.pro
 - sed -i -e 's:-O2:-O0 -fprofile-arcs -ftest-coverage:g' -e 's:-Wl,-O1:-Wl,-O1 -lgcov --coverage:g' Makefile
 - build-wrapper-linux-x86-64 --out-dir bw-output make
 - ./STIGQter tests

after_success:
 - for x in src/*.cpp; do LC_ALL=en gcov --branch-probabilities --branch-counts ${x} -o .; done
 - sonar-scanner
 - coveralls --gcov-options '\-lp'
 - bash <(curl -s https://codecov.io/bash)
