language: cpp
compiler: gcc
dist: bionic

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install qtbase5-dev qt5-qmake qt5-default
 - sudo apt-get install libtidy-dev libzip-dev
 - sudo apt-get install zlib1g-dev
 - wget https://github.com/jmcnamara/libxlsxwriter/archive/RELEASE_0.8.7.tar.gz
 - tar -zxf RELEASE_0.8.7.tar.gz
 - pushd libxlsxwriter-RELEASE_0.8.7 && make && sudo make install INSTALL_DIR=/usr && popd

script:
 - sed -i -e 's:INCLUDEPATH[ ]*=[ ]*:INCLUDEPATH = /usr/include/tidy :g' STIGQter.pro
 - qmake STIGQter.pro
 - make
