language: cpp
compiler: gcc
dist: bionic

addons:
        sonarcloud:
                organization: "squinky86"
                token:
                        secure: "1627f17c5f4b2974c221d3b6fcd2e0c4bebb6ecf"

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install qtbase5-dev qt5-qmake qt5-default
 - sudo apt-get install libtidy-dev libzip-dev
 - sudo apt-get install zlib1g-dev
 - wget https://github.com/jmcnamara/libxlsxwriter/archive/RELEASE_0.8.8.tar.gz
 - tar -zxf RELEASE_0.8.8.tar.gz
 - pushd libxlsxwriter-RELEASE_0.8.8 && make && sudo make install INSTALL_DIR=/usr && popd

script:
 - sed -i -e 's:INCLUDEPATH[ ]*=[ ]*:INCLUDEPATH = /usr/include/tidy :g' STIGQter.pro
 - for x in `find /home/travis/.sonar/cache -name "libinterceptor-x86_64.so"`; do cp ${x} ${x/x86_64/haswell}; done
 - qmake STIGQter.pro
 - build-wrapper-linux-x86-64 --out-dir bw-output make
 - sonar-scanner
